import { generateText } from "ai";
import { openai } from "@ai-sdk/openai";
import type { DocFile } from "../types.js";

const DOC_MAP_PROMPT = `You are an expert technical writer. Analyze the following documentation files and create a documentation map.

For EACH documentation file, provide:
- **Purpose**: What this file documents (1 sentence)
- **When to update**: What code changes would require updating this file
- **Related files**: Other docs that often need updates together with this one

Format as a compact list. Be concise - each file entry should be 2-3 lines max.

Example format:
### path/to/file.md
- Purpose: Documents the REST API endpoints
- When to update: New endpoints, endpoint changes, parameter changes
- Related: api-reference.md, examples.md

---

Documentation files to analyze:
`;

/**
 * Generate a documentation map based on existing documentation
 */
export async function generateDocMap(docs: DocFile[]): Promise<string> {
  if (docs.length === 0) {
    return getDefaultDocMap();
  }

  // Only send file paths and first ~500 chars of content to keep prompt small
  const docsContent = docs
    .map((doc) => {
      const preview = doc.content.slice(0, 500);
      const truncated = doc.content.length > 500 ? "\n[...]" : "";
      return `### ${doc.path}\n${preview}${truncated}`;
    })
    .join("\n\n---\n\n");

  const { text } = await generateText({
    model: openai("gpt-4o-mini"),
    prompt: DOC_MAP_PROMPT + docsContent,
    maxTokens: 1500,
  });

  return `# Documentation Map

_Generated by JanusDoc. Describes what each doc file is for and when it needs updates._

${text}
`;
}

/**
 * Default doc map when no docs exist
 */
function getDefaultDocMap(): string {
  return `# Documentation Map

_No documentation files found. Run \`janusdoc init\` after adding docs._
`;
}

