import { Octokit } from "@octokit/rest";
import type { PRInfo, AnalysisResult } from "../types.js";

/**
 * Create an Octokit instance
 */
export function createOctokit(token?: string): Octokit {
  const auth = token || process.env.GITHUB_TOKEN;

  if (!auth) {
    throw new Error(
      "GitHub token not found. Set GITHUB_TOKEN environment variable or use --token flag.",
    );
  }

  return new Octokit({ auth });
}

/**
 * Parse owner/repo string
 */
export function parseRepo(repo: string): { owner: string; repo: string } {
  const [owner, repoName] = repo.split("/");

  if (!owner || !repoName) {
    throw new Error("Invalid repository format. Use owner/repo format.");
  }

  return { owner, repo: repoName };
}

/**
 * Get PR information from GitHub
 */
export async function getPRInfo(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<PRInfo> {
  try {
    const { data: pr } = await octokit.pulls.get({
      owner,
      repo,
      pull_number: prNumber,
    });

    return {
      number: pr.number,
      title: pr.title,
      baseBranch: pr.base.ref,
      headBranch: pr.head.ref,
      owner,
      repo,
    };
  } catch (error) {
    const status = (error as { status?: number }).status;

    if (status === 404) {
      throw new Error(
        `Could not find PR #${prNumber} in ${owner}/${repo}.\n` +
          `   Possible causes:\n` +
          `   - The PR number or repository name is incorrect\n` +
          `   - The repository is private and your token doesn't have access\n` +
          `   - Your token needs the 'repo' scope for private repositories`,
      );
    }

    if (status === 401) {
      throw new Error(`Authentication failed. Your GitHub token may be invalid or expired.`);
    }

    if (status === 403) {
      throw new Error(
        `Access forbidden. Your GitHub token doesn't have permission to access this repository.\n` +
          `   Make sure your token has the 'repo' scope for private repositories.`,
      );
    }

    throw error;
  }
}

/**
 * Format analysis result as a PR comment
 */
export function formatComment(result: AnalysisResult): string {
  if (result.suggestions.length === 0) {
    return "";
  }

  let comment = `## 📚 JanusDoc - Documentation Update Suggestions\n\n`;
  comment += `${result.summary}\n\n`;

  for (const suggestion of result.suggestions) {
    comment += `### 📄 \`${suggestion.docPath}\`\n\n`;
    comment += `**Reason:** ${suggestion.reason}\n\n`;
    comment += `<details>\n<summary>📝 Suggested updated content (click to expand)</summary>\n\n`;
    comment += `\`\`\`markdown\n${suggestion.updatedContent}\n\`\`\`\n\n`;
    comment += `</details>\n\n`;
    comment += "---\n\n";
  }

  comment += `_This comment was generated by [JanusDoc](https://github.com/janusdoc/janusdoc)._`;

  return comment;
}

/**
 * Post a comment on a PR
 */
export async function postPRComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  body: string,
): Promise<void> {
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body,
  });
}

/**
 * Find existing JanusDoc comment on a PR
 */
export async function findExistingComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
): Promise<number | null> {
  const { data: comments } = await octokit.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  });

  const janusDocComment = comments.find((comment) =>
    comment.body?.includes("## 📚 JanusDoc - Documentation Update Suggestions"),
  );

  return janusDocComment?.id ?? null;
}

/**
 * Update an existing PR comment
 */
export async function updatePRComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  commentId: number,
  body: string,
): Promise<void> {
  await octokit.issues.updateComment({
    owner,
    repo,
    comment_id: commentId,
    body,
  });
}

/**
 * Post or update a JanusDoc comment on a PR
 */
export async function upsertPRComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  body: string,
): Promise<void> {
  const existingCommentId = await findExistingComment(octokit, owner, repo, prNumber);

  if (existingCommentId) {
    await updatePRComment(octokit, owner, repo, existingCommentId, body);
  } else {
    await postPRComment(octokit, owner, repo, prNumber, body);
  }
}
