import { generateText } from "ai";
import { openai } from "@ai-sdk/openai";
import type { DocFile } from "../types.js";

const STYLEGUIDE_PROMPT = `You are an expert technical writer. Analyze the following documentation files and extract a comprehensive style guide that captures the writing patterns, conventions, and style used.

Your style guide should include:
1. **Tone & Voice**: How formal/informal, use of pronouns (you, we, they), active vs passive voice
2. **Structure**: How documents are organized, heading patterns, use of sections
3. **Formatting**: Code block conventions, use of bold/italics, list styles
4. **Conventions**: How APIs are documented, parameter descriptions, examples format
5. **Language**: Technical terminology usage, jargon level, sentence complexity

Output the style guide in Markdown format. Be specific and provide examples from the actual documentation where relevant.

---

Documentation files to analyze:
`;

/**
 * Generate a styleguide based on existing documentation
 */
export async function generateStyleguide(docs: DocFile[]): Promise<string> {
  if (docs.length === 0) {
    return getDefaultStyleguide();
  }

  const docsContent = docs.map((doc) => `### ${doc.path}\n\n${doc.content}`).join("\n\n---\n\n");

  const { text } = await generateText({
    model: openai("gpt-4o-mini"),
    prompt: STYLEGUIDE_PROMPT + docsContent,
    maxTokens: 2000,
  });

  return `# Auto-Generated Style Guide

_Generated by JanusDoc based on analysis of ${docs.length} documentation file(s)._

${text}
`;
}

/**
 * Default styleguide when no docs exist
 */
function getDefaultStyleguide(): string {
  return `# Auto-Generated Style Guide

_No existing documentation found. Using default style guide._

## Tone & Voice
- Use second person ("you") when addressing the reader
- Keep a professional but approachable tone
- Use active voice when possible

## Structure
- Start each document with a brief overview
- Use descriptive headings in sentence case
- Break content into logical sections

## Formatting
- Use fenced code blocks with language annotations
- Use bold for UI elements and important terms
- Use inline code for file names, function names, and commands

## Conventions
- Include code examples for all major features
- Document parameters in tables when applicable
- Provide "Getting Started" sections for complex features

## Language
- Define technical terms on first use
- Keep sentences concise and focused
- Use bullet points for lists of items
`;
}
